import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import { useApp } from '../contexts/AppContext';
import { generateItinerary } from '../services/itineraryService';
import MapView from '../components/MapView';
import { 
  Clock, MapPin, Navigation, IndianRupee, Users, Compass, 
  ChevronDown, ChevronUp, Share2, Bookmark, Play, Download, 
  AlertTriangle, Sparkles, Map as MapIcon, List, Check, ArrowRight,
  Utensils, Hotel, Phone, ExternalLink, Calendar, Shield
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function Itinerary() {
  const location = useLocation();
  const navigate = useNavigate();
  const { startTrip, toggleFavorite, isFavorite } = useApp();

  const [itinerary, setItinerary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeDay, setActiveDay] = useState(1);
  const [activeViewTab, setActiveViewTab] = useState('timeline'); // 'timeline' | 'map'
  const [showCostBreakdown, setShowCostBreakdown] = useState(true);
  const [savedOffline, setSavedOffline] = useState(false);
  const [copied, setCopied] = useState(false);

  const planningData = location.state?.planningData || {
    destinationId: 'dest_vjw',
    days: 2,
    travelers: 2,
    totalBudget: 4000,
    startTime: '09:00 AM',
    interests: ['Heritage', 'Spiritual', 'Nature'],
    travelStyle: 'Balanced',
    pace: 'Balanced'
  };

  useEffect(() => {
    setLoading(true);
    try {
      const generated = generateItinerary(planningData);
      setItinerary(generated);
    } catch (error) {
      console.error('Failed to generate itinerary:', error);
    } finally {
      setTimeout(() => setLoading(false), 500);
    }
  }, [location.state]);

  const handleStartTrip = () => {
    if (!itinerary) return;
    startTrip(itinerary);
    navigate('/my-trip');
  };

  // Save trip to Offline LocalStorage
  const handleSaveOffline = () => {
    if (!itinerary) return;
    try {
      const existing = JSON.parse(localStorage.getItem('saha_offline_trips') || '[]');
      const newTrip = {
        ...itinerary,
        savedAt: new Date().toISOString(),
        id: `offline_${Date.now()}`
      };
      existing.unshift(newTrip);
      localStorage.setItem('saha_offline_trips', JSON.stringify(existing));
      setSavedOffline(true);
      setTimeout(() => setSavedOffline(false), 3000);
    } catch (e) {
      console.error('Failed to save offline:', e);
    }
  };

  // Download printable / standalone offline trip file
  const handleDownloadOfflineFile = () => {
    if (!itinerary) return;
    const dest = itinerary.destination?.name || 'Andhra Pradesh';
    let fileContent = `====================================================\n`;
    fileContent += `  SAHA SMART LOCAL TRAVEL COMPANION — OFFLINE TRIP PLAN\n`;
    fileContent += `  Destination: ${dest} (${itinerary.destination?.district} District)\n`;
    fileContent += `  Duration: ${itinerary.days} Day(s) | Travelers: ${itinerary.travelers}\n`;
    fileContent += `  Estimated Budget: ₹${itinerary.grandTotalCost} (Per person: ₹${itinerary.costPerPerson})\n`;
    fileContent += `====================================================\n\n`;

    itinerary.dailyPlans.forEach(day => {
      fileContent += `--- DAY ${day.day}: ${day.theme} ---\n`;
      day.stops.forEach(stop => {
        if (stop.type === 'attraction') {
          fileContent += `[${stop.time} – ${stop.departureTime}] 🏛️ ${stop.title}\n`;
          fileContent += `   Category: ${stop.category} | Duration: ${stop.suggestedDurationMins} mins\n`;
          fileContent += `   Transit from last: ${stop.travelDistanceFromPrev} km via ${stop.transportMode} (~₹${stop.transportCost})\n`;
          fileContent += `   Entry fee: ₹${stop.entryFeePerPerson} per person\n`;
          fileContent += `   Tip: ${stop.tips || 'Explore comfortably'}\n\n`;
        } else if (stop.type === 'meal') {
          fileContent += `[${stop.time} – ${stop.departureTime}] 🍛 ${stop.mealType}: ${stop.title}\n`;
          fileContent += `   ${stop.description}\n`;
          fileContent += `   Est. Cost: ₹${stop.costPerPerson} per person\n\n`;
        }
      });
      fileContent += `\n`;
    });

    fileContent += `--- EMERGENCY CONTACTS IN ANDHRA PRADESH ---\n`;
    fileContent += `National Emergency: 112\n`;
    fileContent += `Ambulance & Trauma: 108\n`;
    fileContent += `Tourist Helpline: 1363\n`;
    fileContent += `Police: 100\n`;
    fileContent += `Women Helpline: 1091\n\n`;
    fileContent += `Generated by SAHA — Smart Assistance for Tourists in Andhra Pradesh\n`;

    const blob = new Blob([fileContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SAHA_Offline_Trip_${dest.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = () => {
    if (!itinerary) return;
    const shareText = `Check out my SAHA itinerary for ${itinerary.destination?.name}: ${itinerary.days} days, estimated ₹${itinerary.grandTotalCost}. Powered by SAHA.`;
    if (navigator.share) {
      navigator.share({ title: `SAHA Itinerary - ${itinerary.destination?.name}`, text: shareText, url: window.location.href }).catch(() => {});
    } else {
      navigator.clipboard.writeText(shareText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  if (loading || !itinerary) {
    return (
      <div className="min-h-screen bg-[#F7FBFC] flex flex-col items-center justify-center pt-24 px-4">
        <div className="w-16 h-16 rounded-3xl overflow-hidden p-1 bg-white border border-teal-500/40 shadow-xl animate-bounce mb-4">
          <img src="/logo.png" alt="SAHA" className="w-full h-full object-contain" />
        </div>
        <h2 className="text-xl font-black text-[#0B2545]">SAHA AI is Generating Your AP Journey...</h2>
        <p className="text-xs text-slate-500 mt-1">Optimizing routes, local food breaks, and verified stays...</p>
      </div>
    );
  }

  const currentDayPlan = itinerary.dailyPlans.find(d => d.day === activeDay) || itinerary.dailyPlans[0];
  const attractionStops = currentDayPlan.stops.filter(s => s.type === 'attraction');

  return (
    <div className="min-h-screen bg-[#F7FBFC] pt-24 pb-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header Hero Banner */}
        <div className="bg-gradient-to-r from-[#031926] via-[#0B2545] to-[#0077B6] rounded-3xl p-6 sm:p-10 text-white shadow-xl mb-8 relative overflow-hidden">
          <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-6 relative z-10">
            <div>
              <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-teal-500/20 text-[#00A896] text-xs font-black uppercase tracking-wider mb-2 border border-teal-500/30">
                <Sparkles size={13} /> Tailored AI Journey
              </div>
              <h1 className="text-2xl sm:text-4xl font-black tracking-tight">
                {itinerary.destination.name} Explorer
              </h1>
              <p className="text-xs sm:text-sm text-slate-200 mt-1 flex items-center gap-2">
                <span>📍 {itinerary.destination.district} District</span> • 
                <span>⏱️ {itinerary.days} Day(s)</span> • 
                <span>👥 {itinerary.travelers} Travelers</span>
              </p>

              {/* Group Compromise Note */}
              {itinerary.groupCompromiseNote && (
                <div className="mt-3 p-3 bg-teal-500/20 rounded-xl border border-teal-400/40 text-xs font-bold text-teal-200">
                  {itinerary.groupCompromiseNote}
                </div>
              )}

              {/* Weather Alert */}
              {itinerary.weatherAlert && (
                <div className="mt-2 p-3 bg-amber-500/20 rounded-xl border border-amber-400/40 text-xs font-bold text-amber-200">
                  {itinerary.weatherAlert}
                </div>
              )}
            </div>

            {/* Top Action Buttons */}
            <div className="flex flex-wrap items-center gap-2.5">
              <button
                onClick={handleSaveOffline}
                className="px-4 py-2.5 bg-white/10 hover:bg-white/20 text-white rounded-xl text-xs font-bold border border-white/25 backdrop-blur-sm transition-all flex items-center gap-1.5"
              >
                {savedOffline ? <Check size={14} className="text-emerald-400" /> : <Bookmark size={14} />}
                <span>{savedOffline ? 'Saved for Offline!' : 'Save for Offline'}</span>
              </button>

              <button
                onClick={handleDownloadOfflineFile}
                className="px-4 py-2.5 bg-white/10 hover:bg-white/20 text-white rounded-xl text-xs font-bold border border-white/25 backdrop-blur-sm transition-all flex items-center gap-1.5"
                title="Download text summary for offline view"
              >
                <Download size={14} />
                <span>Download Offline</span>
              </button>

              <button
                onClick={handleShare}
                className="p-2.5 bg-white/10 hover:bg-white/20 text-white rounded-xl border border-white/25 backdrop-blur-sm"
              >
                <Share2 size={16} />
              </button>

              <button
                onClick={handleStartTrip}
                className="px-6 py-2.5 bg-gradient-to-r from-[#F59E0B] to-[#E76F51] hover:from-[#D97706] hover:to-[#D46045] text-white rounded-xl text-xs font-black shadow-lg shadow-amber-500/25 transition-all transform hover:-translate-y-0.5 flex items-center gap-2"
              >
                <Play size={14} className="fill-white" /> Start This Journey
              </button>
            </div>
          </div>

          {/* Quick Metrics Bar */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-8 pt-6 border-t border-white/10 text-xs">
            <div className="bg-white/10 rounded-2xl p-3 backdrop-blur-sm">
              <span className="text-slate-300 text-[10px] uppercase font-bold">Total Estimated Budget</span>
              <p className="text-base font-black text-white mt-0.5">₹{itinerary.grandTotalCost.toLocaleString()}</p>
            </div>
            <div className="bg-white/10 rounded-2xl p-3 backdrop-blur-sm">
              <span className="text-slate-300 text-[10px] uppercase font-bold">Per Person Cost</span>
              <p className="text-base font-black text-teal-300 mt-0.5">₹{itinerary.costPerPerson.toLocaleString()}</p>
            </div>
            <div className="bg-white/10 rounded-2xl p-3 backdrop-blur-sm">
              <span className="text-slate-300 text-[10px] uppercase font-bold">Total Sights & Stops</span>
              <p className="text-base font-black text-white mt-0.5">{itinerary.summary.totalStops} Attractions</p>
            </div>
            <div className="bg-white/10 rounded-2xl p-3 backdrop-blur-sm">
              <span className="text-slate-300 text-[10px] uppercase font-bold">Total Distance</span>
              <p className="text-base font-black text-white mt-0.5">~{itinerary.totalDistanceKm} km</p>
            </div>
          </div>
        </div>

        {/* Multi-Day Tabs & View Toggle */}
        <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
          
          {/* Day Tabs */}
          {itinerary.dailyPlans.length > 1 && (
            <div className="flex flex-wrap gap-2">
              {itinerary.dailyPlans.map(day => (
                <button
                  key={day.day}
                  onClick={() => setActiveDay(day.day)}
                  className={`px-5 py-2.5 rounded-2xl text-xs font-black transition-all ${
                    activeDay === day.day
                      ? 'bg-gradient-to-r from-[#0077B6] to-[#00A896] text-white shadow-md'
                      : 'bg-white text-slate-700 hover:bg-slate-50 border border-slate-200'
                  }`}
                >
                  Day {day.day}: {day.theme.split('&')[0]}
                </button>
              ))}
            </div>
          )}

          {/* View Mode Toggle: Timeline vs Leaflet Map */}
          <div className="inline-flex p-1 bg-white rounded-2xl border border-slate-200 shadow-xs">
            <button
              onClick={() => setActiveViewTab('timeline')}
              className={`px-4 py-1.5 rounded-xl text-xs font-black transition-all flex items-center gap-1.5 ${
                activeViewTab === 'timeline'
                  ? 'bg-[#0077B6] text-white'
                  : 'text-slate-600 hover:text-[#0077B6]'
              }`}
            >
              <List size={14} /> Timeline View
            </button>
            <button
              onClick={() => setActiveViewTab('map')}
              className={`px-4 py-1.5 rounded-xl text-xs font-black transition-all flex items-center gap-1.5 ${
                activeViewTab === 'map'
                  ? 'bg-[#0077B6] text-white'
                  : 'text-slate-600 hover:text-[#0077B6]'
              }`}
            >
              <MapIcon size={14} /> Map Route
            </button>
          </div>
        </div>

        {/* Main Content: Timeline or Map */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          <div className="lg:col-span-8 space-y-6">
            
            {activeViewTab === 'timeline' ? (
              <div className="space-y-4">
                {currentDayPlan.stops.map((stop, idx) => (
                  <motion.div
                    key={stop.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className={`rounded-3xl p-6 border transition-all ${
                      stop.type === 'meal'
                        ? 'bg-amber-50/40 border-amber-200/70'
                        : 'bg-white border-teal-900/10 shadow-xs hover:shadow-md'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-4 mb-3">
                      <div className="flex items-center gap-3">
                        <span className="px-3 py-1 bg-[#031926] text-teal-300 font-black text-xs rounded-xl shadow-xs">
                          {stop.time}
                        </span>
                        <div>
                          <span className={`text-[10px] font-black uppercase ${stop.type === 'meal' ? 'text-amber-700' : 'text-[#00838F]'}`}>
                            {stop.type === 'meal' ? '🍛 Meal Break' : `🏛️ ${stop.category}`}
                          </span>
                          <h3 className="text-base font-black text-[#0B2545]">{stop.title}</h3>
                        </div>
                      </div>

                      {stop.type === 'attraction' && (
                        <span className="text-xs font-bold text-slate-500 bg-slate-100 px-2.5 py-1 rounded-lg">
                          ⏱️ {stop.suggestedDurationMins} mins
                        </span>
                      )}
                    </div>

                    <p className="text-xs text-slate-600 leading-relaxed mb-3">
                      {stop.description}
                    </p>

                    {/* Metadata Footer */}
                    <div className="pt-3 border-t border-slate-100 flex flex-wrap items-center justify-between gap-2 text-xs">
                      {stop.type === 'attraction' ? (
                        <>
                          <span className="text-slate-500 font-medium">
                            🚗 {stop.travelDistanceFromPrev} km via {stop.transportMode} (~₹{stop.transportCost})
                          </span>
                          <span className="font-bold text-[#0B2545]">
                            Entry: {stop.entryFeePerPerson > 0 ? `₹${stop.entryFeePerPerson}/person` : 'Free Entry'}
                          </span>
                        </>
                      ) : (
                        <>
                          <span className="text-amber-800 font-bold">
                            🍴 {stop.cuisine || 'Authentic Andhra Meals'}
                          </span>
                          <span className="font-black text-[#0B2545]">
                            Est: ₹{stop.costPerPerson}/person
                          </span>
                        </>
                      )}
                    </div>
                  </motion.div>
                ))}
              </div>
            ) : (
              /* Map View for the selected day */
              <div className="bg-white rounded-3xl p-3 shadow-md border border-slate-200 h-[550px] overflow-hidden">
                <MapView stops={attractionStops} center={itinerary.destination.coordinates} />
              </div>
            )}

            {/* Recommended Hotel Card for Multi-Day Trips */}
            {itinerary.recommendedHotel && (
              <div className="bg-white rounded-3xl p-6 shadow-sm border border-teal-900/10 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                  <div className="w-14 h-14 rounded-2xl bg-amber-50 text-amber-700 flex items-center justify-center flex-shrink-0">
                    <Hotel size={26} />
                  </div>
                  <div>
                    <span className="text-[10px] font-black uppercase text-amber-600 bg-amber-50 px-2 py-0.5 rounded-md">
                      Overnight Stay Recommendation
                    </span>
                    <h4 className="text-base font-black text-[#0B2545] mt-1">{itinerary.recommendedHotel.name}</h4>
                    <p className="text-xs text-slate-500">{itinerary.recommendedHotel.location} • ₹{itinerary.recommendedHotel.pricePerNight}/night</p>
                  </div>
                </div>

                <a
                  href={itinerary.recommendedHotel.bookingLink || '#'}
                  target="_blank"
                  rel="noreferrer"
                  className="px-5 py-2.5 bg-[#0077B6] hover:bg-[#00695C] text-white rounded-xl text-xs font-black flex items-center gap-1.5 transition-colors"
                >
                  Book Hotel <ExternalLink size={13} />
                </a>
              </div>
            )}

          </div>

          {/* Right Sidebar: Cost Breakdown & Offline Guarantee */}
          <div className="lg:col-span-4 space-y-6">
            
            {/* Cost Breakdown Card */}
            <div className="bg-white rounded-3xl p-6 shadow-sm border border-teal-900/10 space-y-4">
              <h3 className="text-base font-black text-[#0B2545] flex items-center justify-between">
                <span>Trip Cost Breakdown</span>
                <span className="text-xs font-black text-emerald-600">Verified Budget</span>
              </h3>

              <div className="space-y-2.5 text-xs">
                <div className="flex justify-between text-slate-600">
                  <span>🏛️ Entry Fees (Total Group):</span>
                  <span className="font-bold text-[#0B2545]">₹{itinerary.summary.breakdown.entryFees}</span>
                </div>
                <div className="flex justify-between text-slate-600">
                  <span>🚗 Local Transit & Auto:</span>
                  <span className="font-bold text-[#0B2545]">₹{itinerary.summary.breakdown.transport}</span>
                </div>
                <div className="flex justify-between text-slate-600">
                  <span>🍛 Meals & Dining:</span>
                  <span className="font-bold text-[#0B2545]">₹{itinerary.summary.breakdown.food}</span>
                </div>
                {itinerary.summary.breakdown.accommodation > 0 && (
                  <div className="flex justify-between text-slate-600">
                    <span>🏨 Hotel Accommodation:</span>
                    <span className="font-bold text-[#0B2545]">₹{itinerary.summary.breakdown.accommodation}</span>
                  </div>
                )}
                <div className="pt-3 border-t border-slate-100 flex justify-between text-sm font-black text-[#0B2545]">
                  <span>Total Journey Cost:</span>
                  <span className="text-[#0077B6]">₹{itinerary.grandTotalCost}</span>
                </div>
              </div>

              <div className="p-3 bg-teal-50/70 rounded-2xl text-[11px] text-[#00838F] font-bold">
                ✓ All costs are calculated using standard 2026 Andhra Pradesh tourism and transport tariffs.
              </div>
            </div>

            {/* Offline Capability Box */}
            <div className="bg-gradient-to-br from-[#031926] to-[#0B2545] text-white rounded-3xl p-6 shadow-md space-y-3">
              <span className="text-[10px] font-black uppercase text-teal-300 bg-teal-500/20 px-2.5 py-1 rounded-md">
                📱 Offline Travel Ready
              </span>
              <h4 className="text-sm font-black text-white">No Internet During Travel?</h4>
              <p className="text-xs text-slate-300 leading-relaxed">
                Save this journey or download the offline file. You can access all timings, restaurant names, and emergency numbers even in remote areas.
              </p>
              <button
                onClick={handleSaveOffline}
                className="w-full py-2.5 bg-gradient-to-r from-[#00A896] to-[#0077B6] hover:from-[#00838F] hover:to-[#0A3D62] text-white rounded-xl text-xs font-black transition-all shadow-sm flex items-center justify-center gap-1.5"
              >
                <Bookmark size={14} /> Save to My Offline Trips
              </button>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
}
