import React from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useApp } from '../contexts/AppContext';
import { CheckCircle2, Download, Home, Plus, MapPin, IndianRupee, Sparkles, Calendar, Users, ArrowRight } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend } from 'recharts';
import { motion } from 'framer-motion';

export default function TripComplete() {
  const { currentTrip } = useApp();
  const navigate = useNavigate();
  const location = useLocation();

  const trip = location.state?.trip || currentTrip;
  const destination = trip?.destination || { name: 'Andhra Pradesh', state: 'Andhra Pradesh' };
  const travelers = trip?.summary?.travelers || trip?.planningParams?.travelers || 1;
  const plannedBudget = trip?.planningParams?.totalBudget || trip?.summary?.estimatedCostAvg || 1500;
  
  // Calculate real category spend or fallback to itinerary breakdown
  const expenses = trip?.expenses || [];
  let expenseData = [];

  if (expenses.length > 0) {
    const categoryTotals = {};
    expenses.forEach(e => {
      categoryTotals[e.category] = (categoryTotals[e.category] || 0) + Number(e.amount);
    });
    const colors = {
      Food: '#F59E0B',
      Transport: '#00838F',
      Activities: '#0077B6',
      Accommodation: '#00695C',
      Shopping: '#EC4899',
      Other: '#64748B'
    };
    expenseData = Object.keys(categoryTotals).map(cat => ({
      name: cat,
      value: categoryTotals[cat],
      color: colors[cat] || '#0077B6'
    }));
  } else {
    // Breakdown from planned itinerary
    const bd = trip?.costBreakdown || { transport: 250, entryFees: 200, food: 350 };
    expenseData = [
      { name: 'Transport', value: bd.transport || 250, color: '#00838F' },
      { name: 'Entry Fees & Activities', value: bd.entryFees || 200, color: '#0077B6' },
      { name: 'Food & Dining', value: bd.food || 350, color: '#F59E0B' },
    ];
  }

  const actualSpent = expenseData.reduce((acc, curr) => acc + curr.value, 0);
  const remaining = plannedBudget - actualSpent;
  const isOverBudget = remaining < 0;

  const handleDownloadSummary = () => {
    const summaryText = `
========================================
       SAHA TRAVEL SUMMARY REPORT
   Your Smart Local Travel Companion
========================================

Destination: ${destination.name}, ${destination.state || 'Andhra Pradesh'}
Travelers: ${travelers}
Planned Budget: INR ${plannedBudget}
Actual Expenses: INR ${actualSpent}
Net Balance: INR ${remaining} (${isOverBudget ? 'Over Budget' : 'Under Budget'})

--- ITINERARY STOPS COMPLETED ---
${(trip?.stops || []).map((s, i) => `${i + 1}. ${s.name} (${s.duration || 'Visit'}) - Entry: ${s.entryFee || 'Free'}`).join('\n')}

--- EXPENSE BREAKDOWN ---
${expenseData.map(e => `• ${e.name}: INR ${e.value}`).join('\n')}

Generated by SAHA • Plan smarter. Travel easier. Explore confidently.
========================================
`;

    const blob = new Blob([summaryText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SAHA_${destination.name}_Trip_Summary.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-[#F8FAFC] min-h-screen pt-24 pb-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Success Header */}
        <div className="text-center mb-10">
          <motion.div 
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ type: "spring", stiffness: 260, damping: 20 }}
            className="w-20 h-20 bg-emerald-100 rounded-3xl flex items-center justify-center mx-auto mb-4 shadow-sm"
          >
            <CheckCircle2 className="w-10 h-10 text-emerald-600" />
          </motion.div>
          
          <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-emerald-50 text-emerald-800 rounded-full text-xs font-bold uppercase tracking-wider mb-2">
            <Sparkles className="w-3.5 h-3.5" /> Journey Completed
          </div>
          
          <h1 className="text-3xl sm:text-4xl font-black text-[#1B2A4A] mb-2">
            You've Completed Your Trip!
          </h1>
          <p className="text-slate-500 text-sm max-w-lg mx-auto">
            Hope you had an unforgettable experience exploring {destination.name}. Here is your complete travel & expense overview.
          </p>
        </div>

        {/* Top Metric Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
          <div className="bg-white p-5 rounded-3xl shadow-sm border border-slate-200 text-center">
            <div className="w-10 h-10 bg-sky-50 rounded-2xl flex items-center justify-center mx-auto mb-2 text-[#0077B6]">
              <MapPin className="w-5 h-5" />
            </div>
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Destination</p>
            <p className="font-extrabold text-base text-[#1B2A4A]">{destination.name}</p>
          </div>

          <div className="bg-white p-5 rounded-3xl shadow-sm border border-slate-200 text-center">
            <div className="w-10 h-10 bg-amber-50 rounded-2xl flex items-center justify-center mx-auto mb-2 text-amber-600">
              <IndianRupee className="w-5 h-5" />
            </div>
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Total Spent</p>
            <p className="font-extrabold text-base text-[#1B2A4A]">₹{actualSpent}</p>
          </div>

          <div className="bg-white p-5 rounded-3xl shadow-sm border border-slate-200 text-center">
            <div className="w-10 h-10 bg-teal-50 rounded-2xl flex items-center justify-center mx-auto mb-2 text-[#00838F]">
              <Users className="w-5 h-5" />
            </div>
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Group & Places</p>
            <p className="font-extrabold text-base text-[#1B2A4A]">{travelers} Travelers &bull; {trip?.stops?.length || 4} Stops</p>
          </div>
        </div>

        {/* Budget & Expense Breakdown Chart */}
        <div className="bg-white rounded-3xl shadow-sm border border-slate-200 p-6 sm:p-8 mb-8">
          <div className="flex justify-between items-center mb-6 pb-3 border-b border-slate-100">
            <div>
              <h2 className="text-xl font-black text-[#1B2A4A]">Expense Breakdown</h2>
              <p className="text-xs text-slate-500">Planned vs Actual financial distribution</p>
            </div>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
            {/* Pie Chart */}
            <div className="h-64 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={expenseData}
                    cx="50%"
                    cy="50%"
                    innerRadius={55}
                    outerRadius={80}
                    paddingAngle={4}
                    dataKey="value"
                  >
                    {expenseData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(value) => `₹${value}`} />
                  <Legend />
                </PieChart>
              </ResponsiveContainer>
            </div>
            
            {/* Summary details */}
            <div className="space-y-4">
              <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100 space-y-2 text-xs sm:text-sm">
                <div className="flex justify-between">
                  <span className="text-slate-500">Planned Budget:</span>
                  <span className="font-bold text-slate-800">₹{plannedBudget}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Actual Outflow:</span>
                  <span className="font-bold text-slate-800">₹{actualSpent}</span>
                </div>
                <div className="h-px bg-slate-200 my-1" />
                <div className="flex justify-between font-extrabold text-sm">
                  <span className="text-slate-700">Remaining Margin:</span>
                  <span className={remaining >= 0 ? 'text-emerald-600' : 'text-rose-600'}>
                    ₹{remaining}
                  </span>
                </div>
              </div>
              
              <div className={`p-4 rounded-2xl border ${
                isOverBudget ? 'bg-rose-50 border-rose-200 text-rose-800' : 'bg-emerald-50 border-emerald-200 text-emerald-800'
              }`}>
                <h4 className="font-bold text-xs uppercase tracking-wider mb-1">
                  {isOverBudget ? 'Budget Exceeded' : 'Smart Budgeting!'}
                </h4>
                <p className="text-xs">
                  {isOverBudget 
                    ? `You spent ₹${Math.abs(remaining)} more than the initial target.` 
                    : `You saved ₹${remaining} and stayed comfortably within your planned budget.`}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-3 justify-center">
          <button 
            onClick={handleDownloadSummary}
            className="bg-white border-2 border-[#0077B6] text-[#0077B6] hover:bg-sky-50 px-6 py-3.5 rounded-2xl font-bold text-xs transition-colors flex items-center justify-center gap-2 shadow-sm"
          >
            <Download className="w-4 h-4" />
            Download Trip Summary (.txt)
          </button>
          
          <button 
            onClick={() => navigate('/planner')}
            className="bg-[#0077B6] hover:bg-[#00695C] text-white px-7 py-3.5 rounded-2xl font-extrabold text-xs transition-all flex items-center justify-center gap-2 shadow-md shadow-[#0077B6]/20"
          >
            <Plus className="w-4 h-4" />
            Plan Another Trip
          </button>
          
          <button 
            onClick={() => navigate('/')}
            className="bg-slate-800 hover:bg-slate-900 text-white px-6 py-3.5 rounded-2xl font-bold text-xs transition-colors flex items-center justify-center gap-2"
          >
            <Home className="w-4 h-4" />
            Back to Home
          </button>
        </div>

      </div>
    </div>
  );
}
